import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Query, QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { cn } from './lib/utils'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
 title: 'Create Next App',
 description: 'Generated by create next app',
}

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode
}>) {
 const queryClient = new QueryClient()
 return (
  <html lang='en'>
   <QueryClientProvider client={queryClient}>
    <body
     style={{ '--accent-hsl': 'var(--blue-hsl)' }}
     className={cn(inter.className, 'relative')}>
     {children}
    </body>
   </QueryClientProvider>
  </html>
 )
}
